// <auto-generated />
using System;
using MediPOS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediPOS.Infrastructure.Modules.TenancyLicensing.Persistence.Migrations
{
    [DbContext(typeof(MediPosDbContext))]
    partial class MediPosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediPOS.Domain.Modules.AuditSupport.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OccurredAt", "Id");

                    b.HasIndex("TenantId", "EntityType", "EntityId", "OccurredAt");

                    b.ToTable("audit_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_logs_after", "after_json IS NULL OR jsonb_typeof(after_json) = 'object'");

                            t.HasCheckConstraint("ck_audit_logs_before", "before_json IS NULL OR jsonb_typeof(before_json) = 'object'");

                            t.HasCheckConstraint("ck_audit_logs_codes", "(entity_type = 'tenant' AND action IN ('tenant.created', 'tenant.purge_requested')) OR\n(entity_type = 'license' AND action IN ('license.renewed', 'license.suspended', 'license.reactivated')) OR\n(entity_type = 'legal_entity' AND action = 'legal_entity.created') OR\n(entity_type = 'branch' AND action IN ('branch.created', 'branch.main_hub_changed')) OR\n(entity_type = 'membership' AND action IN ('membership.created', 'membership.branches_replaced', 'membership.schedule_replaced', 'membership.deactivated'))");

                            t.HasCheckConstraint("ck_audit_logs_correlation", "correlation_id ~ '^[0-9a-f]{32}$' AND correlation_id <> repeat('0', 32)");

                            t.HasCheckConstraint("ck_audit_logs_identifiers", "actor_id <> '00000000-0000-0000-0000-000000000000'::uuid AND entity_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Branches.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsMainHub")
                        .HasColumnType("boolean")
                        .HasColumnName("is_main_hub");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_tenant_main_hub")
                        .HasFilter("is_main_hub");

                    b.HasIndex("TenantId", "LegalEntityId");

                    b.ToTable("branches", null, t =>
                        {
                            t.HasCheckConstraint("ck_branches_name", "name ~ '[^[:space:]]'");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Branches.LegalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("legal_name");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ruc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.ToTable("legal_entities", null, t =>
                        {
                            t.HasCheckConstraint("ck_legal_entities_name", "legal_name ~ '[^[:space:]]'");

                            t.HasCheckConstraint("ck_legal_entities_ruc", "ruc ~ '[^[:space:]]'");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.IdentityAccess.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "Role")
                        .HasFilter("is_active");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_memberships_tenant_user_active")
                        .HasFilter("is_active");

                    b.ToTable("memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_memberships_activation", "(is_active AND deactivated_at IS NULL) OR (NOT is_active AND deactivated_at IS NOT NULL AND deactivated_at >= created_at)");

                            t.HasCheckConstraint("ck_memberships_role", "role IN ('owner', 'pharmacist', 'cashier')");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.IdentityAccess.MembershipBranch", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.HasKey("TenantId", "MembershipId", "BranchId");

                    b.HasIndex("TenantId", "BranchId");

                    b.ToTable("membership_branches", (string)null);
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.IdentityAccess.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GoogleSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("google_subject");

                    b.HasKey("Id");

                    b.HasIndex("GoogleSubject")
                        .IsUnique()
                        .HasDatabaseName("ux_users_google_subject");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_email", "email ~ '[^[:space:]]'");

                            t.HasCheckConstraint("ck_users_name", "display_name ~ '[^[:space:]]'");

                            t.HasCheckConstraint("ck_users_subject", "google_subject ~ '[^[:space:]]'");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.IdentityAccess.WorkSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "MembershipId", "DayOfWeek", "StartTime", "EndTime")
                        .IsUnique()
                        .HasDatabaseName("ux_work_schedules_exact_window");

                    b.ToTable("work_schedules", null, t =>
                        {
                            t.HasCheckConstraint("ck_work_schedules_day", "day_of_week IN ('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun')");

                            t.HasCheckConstraint("ck_work_schedules_window", "start_time < end_time AND end_time < TIME '24:00:00'");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.TenancyLicensing.License", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("MaxBranches")
                        .HasColumnType("integer")
                        .HasColumnName("max_branches");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("licenses", null, t =>
                        {
                            t.HasCheckConstraint("ck_licenses_max_branches", "max_branches BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_licenses_period", "expires_at > starts_at");

                            t.HasCheckConstraint("ck_licenses_status", "status IN ('trial', 'active', 'grace', 'suspended', 'cancelled', 'purge_pending', 'purged')");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.TenancyLicensing.LicenseChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("license_id");

                    b.Property<DateTimeOffset>("NewExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("new_expires_at");

                    b.Property<int>("NewMaxBranches")
                        .HasColumnType("integer")
                        .HasColumnName("new_max_branches");

                    b.Property<DateTimeOffset>("NewStartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("new_starts_at");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_status");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset?>("PreviousExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("previous_expires_at");

                    b.Property<int?>("PreviousMaxBranches")
                        .HasColumnType("integer")
                        .HasColumnName("previous_max_branches");

                    b.Property<DateTimeOffset?>("PreviousStartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("previous_starts_at");

                    b.Property<string>("PreviousStatus")
                        .HasColumnType("text")
                        .HasColumnName("previous_status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "LicenseId", "OccurredAt");

                    b.ToTable("license_changes", null, t =>
                        {
                            t.HasCheckConstraint("ck_license_changes_actor", "actor_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_license_changes_kind", "kind IN ('created', 'renewed', 'suspended', 'reactivated', 'purge_requested')");

                            t.HasCheckConstraint("ck_license_changes_new_max_branches", "new_max_branches BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_license_changes_new_period", "new_expires_at > new_starts_at");

                            t.HasCheckConstraint("ck_license_changes_previous_values", "(kind = 'created' AND previous_status IS NULL AND previous_starts_at IS NULL AND previous_expires_at IS NULL AND previous_max_branches IS NULL) OR (kind <> 'created' AND previous_status IS NOT NULL AND previous_starts_at IS NOT NULL AND previous_expires_at IS NOT NULL AND previous_max_branches IS NOT NULL AND previous_max_branches BETWEEN 1 AND 5 AND previous_expires_at > previous_starts_at)");

                            t.HasCheckConstraint("ck_license_changes_status", "new_status IN ('trial', 'active', 'grace', 'suspended', 'cancelled', 'purge_pending', 'purged') AND (previous_status IS NULL OR previous_status IN ('trial', 'active', 'grace', 'suspended', 'cancelled', 'purge_pending', 'purged'))");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.TenancyLicensing.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TradingName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trading_name");

                    b.HasKey("Id");

                    b.ToTable("tenants", null, t =>
                        {
                            t.HasCheckConstraint("ck_tenants_trading_name", "trading_name ~ '[^[:space:]]'");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.AuditSupport.AuditLog", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.TenancyLicensing.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Branches.Branch", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.TenancyLicensing.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediPOS.Domain.Modules.Branches.LegalEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LegalEntityId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Branches.LegalEntity", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.TenancyLicensing.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.IdentityAccess.Membership", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.TenancyLicensing.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediPOS.Domain.Modules.IdentityAccess.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.IdentityAccess.MembershipBranch", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BranchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediPOS.Domain.Modules.IdentityAccess.Membership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "MembershipId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.IdentityAccess.WorkSchedule", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.IdentityAccess.Membership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "MembershipId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.TenancyLicensing.License", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.TenancyLicensing.Tenant", null)
                        .WithOne("License")
                        .HasForeignKey("MediPOS.Domain.Modules.TenancyLicensing.License", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.TenancyLicensing.LicenseChange", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.TenancyLicensing.License", null)
                        .WithMany("Changes")
                        .HasForeignKey("TenantId", "LicenseId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.TenancyLicensing.License", b =>
                {
                    b.Navigation("Changes");
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.TenancyLicensing.Tenant", b =>
                {
                    b.Navigation("License")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
