// <auto-generated />
using System;
using MediPOS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediPOS.Infrastructure.Modules.Catalog.Persistence.Migrations
{
    [DbContext(typeof(MediPosDbContext))]
    [Migration("20261006192212_AddProductSearchEngine")]
    partial class AddProductSearchEngine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "public", "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "public", "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediPOS.Domain.Modules.AuditSupport.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OccurredAt", "Id");

                    b.HasIndex("TenantId", "EntityType", "EntityId", "OccurredAt");

                    b.ToTable("audit_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_logs_after", "after_json IS NULL OR jsonb_typeof(after_json) = 'object'");

                            t.HasCheckConstraint("ck_audit_logs_before", "before_json IS NULL OR jsonb_typeof(before_json) = 'object'");

                            t.HasCheckConstraint("ck_audit_logs_codes", "(entity_type = 'tenant' AND action IN ('tenant.created', 'tenant.purge_requested')) OR\n(entity_type = 'license' AND action IN ('license.renewed', 'license.suspended', 'license.reactivated')) OR\n(entity_type = 'legal_entity' AND action = 'legal_entity.created') OR\n(entity_type = 'branch' AND action IN ('branch.created', 'branch.main_hub_changed')) OR\n(entity_type = 'membership' AND action IN ('membership.created', 'membership.branches_replaced', 'membership.schedule_replaced', 'membership.deactivated')) OR\n(entity_type = 'business_product' AND action IN ('business_product.created', 'business_product.price_changed', 'business_product.status_changed', 'business_product.units_changed')) OR\n(entity_type = 'purchase' AND action = 'purchase.confirmed') OR\n(entity_type = 'inventory_lot' AND action = 'inventory.adjusted')");

                            t.HasCheckConstraint("ck_audit_logs_correlation", "correlation_id ~ '^[0-9a-f]{32}$' AND correlation_id <> repeat('0', 32)");

                            t.HasCheckConstraint("ck_audit_logs_identifiers", "actor_id <> '00000000-0000-0000-0000-000000000000'::uuid AND entity_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Branches.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsMainHub")
                        .HasColumnType("boolean")
                        .HasColumnName("is_main_hub");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_tenant_main_hub")
                        .HasFilter("is_main_hub");

                    b.HasIndex("TenantId", "LegalEntityId");

                    b.ToTable("branches", null, t =>
                        {
                            t.HasCheckConstraint("ck_branches_name", "name ~ '[^[:space:]]'");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Branches.LegalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("legal_name");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ruc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.ToTable("legal_entities", null, t =>
                        {
                            t.HasCheckConstraint("ck_legal_entities_name", "legal_name ~ '[^[:space:]]'");

                            t.HasCheckConstraint("ck_legal_entities_ruc", "ruc ~ '[^[:space:]]'");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Catalog.BusinessProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("barcode");

                    b.Property<string>("BrandOrLaboratory")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("brand_or_laboratory");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("GlobalProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("global_product_id");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("internal_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("product_type");

                    b.Property<decimal>("RetailPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("retail_price");

                    b.Property<string>("SearchBarcode")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("search_barcode")
                        .UseCollation("C");

                    b.Property<string>("SearchBrand")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("search_brand")
                        .UseCollation("C");

                    b.Property<string>("SearchIngredients")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("search_ingredients")
                        .UseCollation("C");

                    b.Property<string>("SearchInternalCode")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("search_internal_code")
                        .UseCollation("C");

                    b.Property<string>("SearchName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("search_name")
                        .UseCollation("C");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<decimal?>("WholesalePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("wholesale_price");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GlobalProductId");

                    b.HasIndex("SearchBrand")
                        .HasDatabaseName("ix_business_products_search_brand_trgm")
                        .HasFilter("is_active");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchBrand"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchBrand"), new[] { "public.gin_trgm_ops" });

                    b.HasIndex("SearchIngredients")
                        .HasDatabaseName("ix_business_products_search_ingredients_trgm")
                        .HasFilter("is_active AND product_type = 'medicine'");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchIngredients"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchIngredients"), new[] { "public.gin_trgm_ops" });

                    b.HasIndex("SearchName")
                        .HasDatabaseName("ix_business_products_search_name_trgm")
                        .HasFilter("is_active");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchName"), new[] { "public.gin_trgm_ops" });

                    b.HasIndex("TenantId", "Barcode")
                        .HasFilter("barcode IS NOT NULL");

                    b.HasIndex("TenantId", "InternalCode")
                        .IsUnique()
                        .HasDatabaseName("ux_business_products_tenant_internal_code");

                    b.HasIndex("TenantId", "Name");

                    b.HasIndex("TenantId", "SearchBarcode")
                        .HasDatabaseName("ix_business_products_search_barcode")
                        .HasFilter("is_active AND search_barcode IS NOT NULL");

                    b.HasIndex("TenantId", "SearchBrand")
                        .HasDatabaseName("ix_business_products_search_brand")
                        .HasFilter("is_active");

                    b.HasIndex("TenantId", "SearchInternalCode")
                        .HasDatabaseName("ix_business_products_search_code")
                        .HasFilter("is_active");

                    b.HasIndex("TenantId", "SearchName")
                        .HasDatabaseName("ix_business_products_search_name")
                        .HasFilter("is_active");

                    b.ToTable("business_products", null, t =>
                        {
                            t.HasCheckConstraint("ck_business_products_medicine", "(product_type = 'medicine' AND medicine_active_ingredients IS NOT NULL\n    AND cardinality(medicine_active_ingredients) > 0 AND array_position(medicine_active_ingredients, NULL) IS NULL\n    AND array_position(medicine_active_ingredients, '') IS NULL\n    AND medicine_normalized_strength IS NOT NULL AND length(btrim(medicine_normalized_strength)) > 0\n    AND medicine_dosage_form IS NOT NULL AND length(btrim(medicine_dosage_form)) > 0)\nOR (product_type = 'retail' AND medicine_active_ingredients IS NULL AND medicine_normalized_strength IS NULL\n    AND medicine_dosage_form IS NULL AND medicine_route IS NULL AND medicine_sanitary_registration IS NULL)");

                            t.HasCheckConstraint("ck_business_products_normalization", "(medicine_equivalence_key IS NULL AND medicine_normalized_ingredients IS NULL AND medicine_normalized_strengths IS NULL\n    AND medicine_canonical_dosage_form IS NULL AND medicine_canonical_route IS NULL)\nOR (medicine_equivalence_key IS NOT NULL AND medicine_equivalence_key ~ '^[0-9a-f]{64}$'\n    AND medicine_normalized_ingredients IS NOT NULL AND medicine_normalized_strengths IS NOT NULL\n    AND cardinality(medicine_normalized_ingredients) > 0\n    AND array_ndims(medicine_normalized_ingredients) = 1 AND array_ndims(medicine_normalized_strengths) = 1\n    AND cardinality(medicine_normalized_ingredients) = cardinality(medicine_normalized_strengths)\n    AND array_position(medicine_normalized_ingredients, NULL) IS NULL AND array_position(medicine_normalized_strengths, NULL) IS NULL\n    AND array_position(medicine_normalized_ingredients, '') IS NULL AND array_position(medicine_normalized_strengths, '') IS NULL\n    AND medicine_canonical_dosage_form IS NOT NULL AND length(btrim(medicine_canonical_dosage_form)) > 0\n    AND (medicine_canonical_route IS NULL OR length(btrim(medicine_canonical_route)) > 0)\n    AND ((medicine_route IS NULL) = (medicine_canonical_route IS NULL)))");

                            t.HasCheckConstraint("ck_business_products_prices", "retail_price >= 0 AND (wholesale_price IS NULL OR wholesale_price >= 0)");

                            t.HasCheckConstraint("ck_business_products_retail_normalization", "product_type = 'medicine' OR medicine_equivalence_key IS NULL");

                            t.HasCheckConstraint("ck_business_products_text", "length(btrim(internal_code)) > 0 AND internal_code = btrim(internal_code) AND length(btrim(name)) > 0 AND length(btrim(brand_or_laboratory)) > 0 AND (barcode IS NULL OR length(btrim(barcode)) > 0)");

                            t.HasCheckConstraint("ck_business_products_type", "product_type IN ('medicine', 'retail')");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Catalog.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_categories_name", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Catalog.GlobalProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("barcode");

                    b.Property<string>("BrandOrLaboratory")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("brand_or_laboratory");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("product_type");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .HasFilter("barcode IS NOT NULL");

                    b.HasIndex("BrandOrLaboratory");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("global_products", null, t =>
                        {
                            t.HasCheckConstraint("ck_global_products_text", "length(btrim(name)) > 0 AND length(btrim(brand_or_laboratory)) > 0 AND (barcode IS NULL OR length(btrim(barcode)) > 0)");

                            t.HasCheckConstraint("ck_global_products_type", "product_type IN ('medicine', 'retail')");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Catalog.MedicineProfile", b =>
                {
                    b.Property<Guid>("GlobalProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("global_product_id");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("product_type");

                    b.HasKey("GlobalProductId");

                    b.HasIndex("GlobalProductId", "ProductType")
                        .IsUnique();

                    b.ToTable("medicine_profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_medicine_profiles_data", "cardinality(active_ingredients) > 0 AND array_position(active_ingredients, NULL) IS NULL\nAND array_position(active_ingredients, '') IS NULL AND length(btrim(normalized_strength)) > 0\nAND length(btrim(dosage_form)) > 0");

                            t.HasCheckConstraint("ck_medicine_profiles_normalization", "(equivalence_key IS NULL AND normalized_ingredients IS NULL AND normalized_strengths IS NULL\n    AND canonical_dosage_form IS NULL AND canonical_route IS NULL)\nOR (equivalence_key IS NOT NULL AND equivalence_key ~ '^[0-9a-f]{64}$'\n    AND normalized_ingredients IS NOT NULL AND normalized_strengths IS NOT NULL\n    AND cardinality(normalized_ingredients) > 0\n    AND array_ndims(normalized_ingredients) = 1 AND array_ndims(normalized_strengths) = 1\n    AND cardinality(normalized_ingredients) = cardinality(normalized_strengths)\n    AND array_position(normalized_ingredients, NULL) IS NULL AND array_position(normalized_strengths, NULL) IS NULL\n    AND array_position(normalized_ingredients, '') IS NULL AND array_position(normalized_strengths, '') IS NULL\n    AND canonical_dosage_form IS NOT NULL AND length(btrim(canonical_dosage_form)) > 0\n    AND (canonical_route IS NULL OR length(btrim(canonical_route)) > 0)\n    AND ((route IS NULL) = (canonical_route IS NULL)))");

                            t.HasCheckConstraint("ck_medicine_profiles_type", "product_type = 'medicine'");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Catalog.ProductUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_product_id");

                    b.Property<decimal>("ConversionToBase")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("conversion_to_base");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBaseUnit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_base_unit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "BusinessProductId")
                        .IsUnique()
                        .HasDatabaseName("ux_product_units_tenant_product_base")
                        .HasFilter("is_base_unit");

                    b.HasIndex("TenantId", "BusinessProductId", "Name")
                        .IsUnique();

                    b.ToTable("product_units", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_units_base", "NOT is_base_unit OR conversion_to_base = 1");

                            t.HasCheckConstraint("ck_product_units_factor", "conversion_to_base > 0");

                            t.HasCheckConstraint("ck_product_units_name", "name ~ '[^[:space:]]' AND name = btrim(name)");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.IdentityAccess.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "Role")
                        .HasFilter("is_active");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_memberships_tenant_user_active")
                        .HasFilter("is_active");

                    b.ToTable("memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_memberships_activation", "(is_active AND deactivated_at IS NULL) OR (NOT is_active AND deactivated_at IS NOT NULL AND deactivated_at >= created_at)");

                            t.HasCheckConstraint("ck_memberships_role", "role IN ('owner', 'pharmacist', 'cashier')");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.IdentityAccess.MembershipBranch", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.HasKey("TenantId", "MembershipId", "BranchId");

                    b.HasIndex("TenantId", "BranchId");

                    b.ToTable("membership_branches", (string)null);
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.IdentityAccess.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GoogleSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("google_subject");

                    b.HasKey("Id");

                    b.HasIndex("GoogleSubject")
                        .IsUnique()
                        .HasDatabaseName("ux_users_google_subject");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_email", "email ~ '[^[:space:]]'");

                            t.HasCheckConstraint("ck_users_name", "display_name ~ '[^[:space:]]'");

                            t.HasCheckConstraint("ck_users_subject", "google_subject ~ '[^[:space:]]'");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.IdentityAccess.WorkSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "MembershipId", "DayOfWeek", "StartTime", "EndTime")
                        .IsUnique()
                        .HasDatabaseName("ux_work_schedules_exact_window");

                    b.ToTable("work_schedules", null, t =>
                        {
                            t.HasCheckConstraint("ck_work_schedules_day", "day_of_week IN ('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun')");

                            t.HasCheckConstraint("ck_work_schedules_window", "start_time < end_time AND end_time < TIME '24:00:00'");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Inventory.InventoryLot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("batch_number");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("BusinessProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_product_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<decimal>("QuantityAvailableBase")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity_available_base");

                    b.Property<Guid>("SourcePurchaseLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_purchase_line_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id");

                    b.HasIndex("TenantId", "BusinessProductId");

                    b.HasIndex("TenantId", "SourcePurchaseLineId")
                        .IsUnique();

                    b.HasIndex("TenantId", "ExpirationDate", "BranchId")
                        .HasDatabaseName("ix_inventory_lots_expiring")
                        .HasFilter("quantity_available_base > 0 AND expiration_date IS NOT NULL");

                    b.HasIndex("TenantId", "SourcePurchaseLineId", "BusinessProductId");

                    b.HasIndex("TenantId", "BranchId", "BusinessProductId", "ExpirationDate", "CreatedAt", "Id")
                        .HasDatabaseName("ix_inventory_lots_fefo")
                        .HasFilter("quantity_available_base > 0 AND expiration_date IS NOT NULL");

                    b.ToTable("inventory_lots", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_lots_available", "quantity_available_base >= 0");

                            t.HasCheckConstraint("ck_inventory_lots_batch", "batch_number IS NULL OR batch_number ~ '[^[:space:]]'");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Inventory.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("BusinessProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_product_id");

                    b.Property<Guid>("InventoryLotId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_lot_id");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("movement_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<decimal>("QuantityDeltaBase")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity_delta_base");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("SourcePurchaseLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_purchase_line_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id");

                    b.HasIndex("TenantId", "BusinessProductId");

                    b.HasIndex("TenantId", "SourcePurchaseLineId")
                        .IsUnique()
                        .HasFilter("source_purchase_line_id IS NOT NULL");

                    b.HasIndex("TenantId", "InventoryLotId", "OccurredAt");

                    b.HasIndex("TenantId", "SourcePurchaseLineId", "BusinessProductId");

                    b.HasIndex("TenantId", "BranchId", "BusinessProductId", "OccurredAt");

                    b.HasIndex("TenantId", "InventoryLotId", "BranchId", "BusinessProductId", "SourcePurchaseLineId");

                    b.ToTable("stock_movements", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_movements_actor", "actor_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_stock_movements_delta", "(movement_type = 'purchase_receipt' AND quantity_delta_base > 0 AND source_purchase_line_id IS NOT NULL AND reason IS NULL) OR (movement_type = 'adjustment' AND quantity_delta_base <> 0 AND source_purchase_line_id IS NULL AND reason ~ '[^[:space:]]' AND reason = btrim(reason) AND reason IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Purchasing.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedByActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by_actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_actor_id");

                    b.Property<string>("DocumentReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("document_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "DocumentReference")
                        .HasFilter("document_reference IS NOT NULL");

                    b.HasIndex("TenantId", "SupplierId");

                    b.HasIndex("TenantId", "BranchId", "CreatedAt");

                    b.ToTable("purchases", null, t =>
                        {
                            t.HasCheckConstraint("ck_purchases_actors", "created_by_actor_id <> '00000000-0000-0000-0000-000000000000'::uuid AND (confirmed_by_actor_id IS NULL OR confirmed_by_actor_id <> '00000000-0000-0000-0000-000000000000'::uuid)");

                            t.HasCheckConstraint("ck_purchases_status", "(status = 'draft' AND confirmed_at IS NULL AND confirmed_by_actor_id IS NULL) OR (status = 'confirmed' AND confirmed_at IS NOT NULL AND confirmed_by_actor_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Purchasing.PurchaseLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("base_quantity");

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("batch_number");

                    b.Property<Guid>("BusinessProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_product_id");

                    b.Property<decimal>("ConversionToBaseSnapshot")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("conversion_to_base_snapshot");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_cost");

                    b.Property<string>("UnitNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("unit_name_snapshot");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id");

                    b.HasIndex("TenantId", "BusinessProductId");

                    b.HasIndex("TenantId", "PurchaseId");

                    b.ToTable("purchase_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_purchase_lines_cost", "unit_cost >= 0");

                            t.HasCheckConstraint("ck_purchase_lines_quantities", "quantity > 0 AND conversion_to_base_snapshot > 0 AND base_quantity > 0 AND base_quantity = quantity * conversion_to_base_snapshot");

                            t.HasCheckConstraint("ck_purchase_lines_unit_name", "unit_name_snapshot ~ '[^[:space:]]'");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Purchasing.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Contact")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("contact");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Ruc")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ruc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name");

                    b.HasIndex("TenantId", "Ruc")
                        .HasFilter("ruc IS NOT NULL");

                    b.ToTable("suppliers", null, t =>
                        {
                            t.HasCheckConstraint("ck_suppliers_name", "name ~ '[^[:space:]]' AND name = btrim(name)");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.TenancyLicensing.License", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("MaxBranches")
                        .HasColumnType("integer")
                        .HasColumnName("max_branches");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("licenses", null, t =>
                        {
                            t.HasCheckConstraint("ck_licenses_max_branches", "max_branches BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_licenses_period", "expires_at > starts_at");

                            t.HasCheckConstraint("ck_licenses_status", "status IN ('trial', 'active', 'grace', 'suspended', 'cancelled', 'purge_pending', 'purged')");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.TenancyLicensing.LicenseChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("license_id");

                    b.Property<DateTimeOffset>("NewExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("new_expires_at");

                    b.Property<int>("NewMaxBranches")
                        .HasColumnType("integer")
                        .HasColumnName("new_max_branches");

                    b.Property<DateTimeOffset>("NewStartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("new_starts_at");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_status");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset?>("PreviousExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("previous_expires_at");

                    b.Property<int?>("PreviousMaxBranches")
                        .HasColumnType("integer")
                        .HasColumnName("previous_max_branches");

                    b.Property<DateTimeOffset?>("PreviousStartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("previous_starts_at");

                    b.Property<string>("PreviousStatus")
                        .HasColumnType("text")
                        .HasColumnName("previous_status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "LicenseId", "OccurredAt");

                    b.ToTable("license_changes", null, t =>
                        {
                            t.HasCheckConstraint("ck_license_changes_actor", "actor_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_license_changes_kind", "kind IN ('created', 'renewed', 'suspended', 'reactivated', 'purge_requested')");

                            t.HasCheckConstraint("ck_license_changes_new_max_branches", "new_max_branches BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_license_changes_new_period", "new_expires_at > new_starts_at");

                            t.HasCheckConstraint("ck_license_changes_previous_values", "(kind = 'created' AND previous_status IS NULL AND previous_starts_at IS NULL AND previous_expires_at IS NULL AND previous_max_branches IS NULL) OR (kind <> 'created' AND previous_status IS NOT NULL AND previous_starts_at IS NOT NULL AND previous_expires_at IS NOT NULL AND previous_max_branches IS NOT NULL AND previous_max_branches BETWEEN 1 AND 5 AND previous_expires_at > previous_starts_at)");

                            t.HasCheckConstraint("ck_license_changes_status", "new_status IN ('trial', 'active', 'grace', 'suspended', 'cancelled', 'purge_pending', 'purged') AND (previous_status IS NULL OR previous_status IN ('trial', 'active', 'grace', 'suspended', 'cancelled', 'purge_pending', 'purged'))");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.TenancyLicensing.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TradingName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trading_name");

                    b.HasKey("Id");

                    b.ToTable("tenants", null, t =>
                        {
                            t.HasCheckConstraint("ck_tenants_trading_name", "trading_name ~ '[^[:space:]]'");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.AuditSupport.AuditLog", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.TenancyLicensing.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Branches.Branch", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.TenancyLicensing.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediPOS.Domain.Modules.Branches.LegalEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LegalEntityId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Branches.LegalEntity", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.TenancyLicensing.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Catalog.BusinessProduct", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.Catalog.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediPOS.Domain.Modules.Catalog.GlobalProduct", null)
                        .WithMany()
                        .HasForeignKey("GlobalProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MediPOS.Domain.Modules.TenancyLicensing.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("MediPOS.Domain.Modules.Catalog.MedicineData", "Medicine", b1 =>
                        {
                            b1.Property<Guid>("BusinessProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CanonicalDosageForm")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("medicine_canonical_dosage_form");

                            b1.Property<string>("CanonicalRoute")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("medicine_canonical_route");

                            b1.Property<string>("DosageForm")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("medicine_dosage_form");

                            b1.Property<string>("EquivalenceKey")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("medicine_equivalence_key");

                            b1.Property<string>("NormalizedStrength")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("medicine_normalized_strength");

                            b1.Property<string>("Route")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("medicine_route");

                            b1.Property<string>("SanitaryRegistration")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("medicine_sanitary_registration");

                            b1.Property<uint>("Version")
                                .IsConcurrencyToken()
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("xid")
                                .HasColumnName("xmin");

                            b1.PrimitiveCollection<string[]>("_activeIngredients")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("medicine_active_ingredients");

                            b1.PrimitiveCollection<string[]>("_normalizedIngredients")
                                .HasColumnType("text[]")
                                .HasColumnName("medicine_normalized_ingredients");

                            b1.PrimitiveCollection<string[]>("_normalizedStrengths")
                                .HasColumnType("text[]")
                                .HasColumnName("medicine_normalized_strengths");

                            b1.HasKey("BusinessProductId");

                            b1.HasIndex("EquivalenceKey")
                                .HasFilter("medicine_equivalence_key IS NOT NULL");

                            b1.ToTable("business_products");

                            b1.WithOwner()
                                .HasForeignKey("BusinessProductId");
                        });

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Catalog.GlobalProduct", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.Catalog.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Catalog.MedicineProfile", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.Catalog.GlobalProduct", null)
                        .WithOne("MedicineProfile")
                        .HasForeignKey("MediPOS.Domain.Modules.Catalog.MedicineProfile", "GlobalProductId", "ProductType")
                        .HasPrincipalKey("MediPOS.Domain.Modules.Catalog.GlobalProduct", "Id", "ProductType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("MediPOS.Domain.Modules.Catalog.MedicineData", "Data", b1 =>
                        {
                            b1.Property<Guid>("MedicineProfileGlobalProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CanonicalDosageForm")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("canonical_dosage_form");

                            b1.Property<string>("CanonicalRoute")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("canonical_route");

                            b1.Property<string>("DosageForm")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("dosage_form");

                            b1.Property<string>("EquivalenceKey")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("equivalence_key");

                            b1.Property<string>("NormalizedStrength")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("normalized_strength");

                            b1.Property<string>("Route")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("route");

                            b1.Property<string>("SanitaryRegistration")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("sanitary_registration");

                            b1.PrimitiveCollection<string[]>("_activeIngredients")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("active_ingredients");

                            b1.PrimitiveCollection<string[]>("_normalizedIngredients")
                                .HasColumnType("text[]")
                                .HasColumnName("normalized_ingredients");

                            b1.PrimitiveCollection<string[]>("_normalizedStrengths")
                                .HasColumnType("text[]")
                                .HasColumnName("normalized_strengths");

                            b1.HasKey("MedicineProfileGlobalProductId");

                            b1.HasIndex("EquivalenceKey")
                                .HasFilter("equivalence_key IS NOT NULL");

                            b1.ToTable("medicine_profiles");

                            b1.WithOwner()
                                .HasForeignKey("MedicineProfileGlobalProductId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Catalog.ProductUnit", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.Catalog.BusinessProduct", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BusinessProductId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.IdentityAccess.Membership", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.TenancyLicensing.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediPOS.Domain.Modules.IdentityAccess.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.IdentityAccess.MembershipBranch", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BranchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediPOS.Domain.Modules.IdentityAccess.Membership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "MembershipId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.IdentityAccess.WorkSchedule", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.IdentityAccess.Membership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "MembershipId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Inventory.InventoryLot", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BranchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediPOS.Domain.Modules.Catalog.BusinessProduct", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BusinessProductId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediPOS.Domain.Modules.Purchasing.PurchaseLine", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SourcePurchaseLineId", "BusinessProductId")
                        .HasPrincipalKey("TenantId", "Id", "BusinessProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Inventory.StockMovement", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BranchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediPOS.Domain.Modules.Catalog.BusinessProduct", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BusinessProductId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediPOS.Domain.Modules.Purchasing.PurchaseLine", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SourcePurchaseLineId", "BusinessProductId")
                        .HasPrincipalKey("TenantId", "Id", "BusinessProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MediPOS.Domain.Modules.Inventory.InventoryLot", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "InventoryLotId", "BranchId", "BusinessProductId")
                        .HasPrincipalKey("TenantId", "Id", "BranchId", "BusinessProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediPOS.Domain.Modules.Inventory.InventoryLot", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "InventoryLotId", "BranchId", "BusinessProductId", "SourcePurchaseLineId")
                        .HasPrincipalKey("TenantId", "Id", "BranchId", "BusinessProductId", "SourcePurchaseLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_stock_movements_inventory_lots_tenant_id_inventory_lot_id_~1");
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Purchasing.Purchase", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BranchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediPOS.Domain.Modules.Purchasing.Supplier", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SupplierId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Purchasing.PurchaseLine", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.Catalog.BusinessProduct", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BusinessProductId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediPOS.Domain.Modules.Purchasing.Purchase", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PurchaseId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Purchasing.Supplier", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.TenancyLicensing.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.TenancyLicensing.License", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.TenancyLicensing.Tenant", null)
                        .WithOne("License")
                        .HasForeignKey("MediPOS.Domain.Modules.TenancyLicensing.License", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.TenancyLicensing.LicenseChange", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.TenancyLicensing.License", null)
                        .WithMany("Changes")
                        .HasForeignKey("TenantId", "LicenseId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Catalog.GlobalProduct", b =>
                {
                    b.Navigation("MedicineProfile");
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.TenancyLicensing.License", b =>
                {
                    b.Navigation("Changes");
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.TenancyLicensing.Tenant", b =>
                {
                    b.Navigation("License")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
