// <auto-generated />
using System;
using MediPOS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediPOS.Infrastructure.Modules.Branches.Persistence.Migrations
{
    [DbContext(typeof(MediPosDbContext))]
    [Migration("20261006025040_AddLegalEntitiesAndBranches")]
    partial class AddLegalEntitiesAndBranches
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediPOS.Domain.Modules.Branches.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsMainHub")
                        .HasColumnType("boolean")
                        .HasColumnName("is_main_hub");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_tenant_main_hub")
                        .HasFilter("is_main_hub");

                    b.HasIndex("TenantId", "LegalEntityId");

                    b.ToTable("branches", null, t =>
                        {
                            t.HasCheckConstraint("ck_branches_name", "name ~ '[^[:space:]]'");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Branches.LegalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("legal_name");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ruc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.ToTable("legal_entities", null, t =>
                        {
                            t.HasCheckConstraint("ck_legal_entities_name", "legal_name ~ '[^[:space:]]'");

                            t.HasCheckConstraint("ck_legal_entities_ruc", "ruc ~ '[^[:space:]]'");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.TenancyLicensing.License", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("MaxBranches")
                        .HasColumnType("integer")
                        .HasColumnName("max_branches");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("licenses", null, t =>
                        {
                            t.HasCheckConstraint("ck_licenses_max_branches", "max_branches BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_licenses_period", "expires_at > starts_at");

                            t.HasCheckConstraint("ck_licenses_status", "status IN ('trial', 'active', 'grace', 'suspended', 'cancelled', 'purge_pending', 'purged')");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.TenancyLicensing.LicenseChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("license_id");

                    b.Property<DateTimeOffset>("NewExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("new_expires_at");

                    b.Property<int>("NewMaxBranches")
                        .HasColumnType("integer")
                        .HasColumnName("new_max_branches");

                    b.Property<DateTimeOffset>("NewStartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("new_starts_at");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_status");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset?>("PreviousExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("previous_expires_at");

                    b.Property<int?>("PreviousMaxBranches")
                        .HasColumnType("integer")
                        .HasColumnName("previous_max_branches");

                    b.Property<DateTimeOffset?>("PreviousStartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("previous_starts_at");

                    b.Property<string>("PreviousStatus")
                        .HasColumnType("text")
                        .HasColumnName("previous_status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "LicenseId", "OccurredAt");

                    b.ToTable("license_changes", null, t =>
                        {
                            t.HasCheckConstraint("ck_license_changes_actor", "actor_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_license_changes_kind", "kind IN ('created', 'renewed', 'suspended', 'reactivated', 'purge_requested')");

                            t.HasCheckConstraint("ck_license_changes_new_max_branches", "new_max_branches BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_license_changes_new_period", "new_expires_at > new_starts_at");

                            t.HasCheckConstraint("ck_license_changes_previous_values", "(kind = 'created' AND previous_status IS NULL AND previous_starts_at IS NULL AND previous_expires_at IS NULL AND previous_max_branches IS NULL) OR (kind <> 'created' AND previous_status IS NOT NULL AND previous_starts_at IS NOT NULL AND previous_expires_at IS NOT NULL AND previous_max_branches IS NOT NULL AND previous_max_branches BETWEEN 1 AND 5 AND previous_expires_at > previous_starts_at)");

                            t.HasCheckConstraint("ck_license_changes_status", "new_status IN ('trial', 'active', 'grace', 'suspended', 'cancelled', 'purge_pending', 'purged') AND (previous_status IS NULL OR previous_status IN ('trial', 'active', 'grace', 'suspended', 'cancelled', 'purge_pending', 'purged'))");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.TenancyLicensing.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TradingName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trading_name");

                    b.HasKey("Id");

                    b.ToTable("tenants", null, t =>
                        {
                            t.HasCheckConstraint("ck_tenants_trading_name", "trading_name ~ '[^[:space:]]'");
                        });
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Branches.Branch", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.TenancyLicensing.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediPOS.Domain.Modules.Branches.LegalEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LegalEntityId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.Branches.LegalEntity", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.TenancyLicensing.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.TenancyLicensing.License", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.TenancyLicensing.Tenant", null)
                        .WithOne("License")
                        .HasForeignKey("MediPOS.Domain.Modules.TenancyLicensing.License", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.TenancyLicensing.LicenseChange", b =>
                {
                    b.HasOne("MediPOS.Domain.Modules.TenancyLicensing.License", null)
                        .WithMany("Changes")
                        .HasForeignKey("TenantId", "LicenseId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.TenancyLicensing.License", b =>
                {
                    b.Navigation("Changes");
                });

            modelBuilder.Entity("MediPOS.Domain.Modules.TenancyLicensing.Tenant", b =>
                {
                    b.Navigation("License")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
